let CardElements = [
  {
    number: 1,
    id: "Zf1o4Mq",
    title: "A. Bailey Legacy Foundation for Women",
    location: "Winston-Salem, North Carolina",
    link: "https://legacyfoundationforwomen.com/",
  },
  {
    number: 2,
    id: "RffjVYY",
    title: "Associates in Christian Counseling",
    location: "Winston-Salem, North Carolina",
    link: "https://christiancounseling.org/",
  },
  {
    number: 3,
    id: "LHioVBp",
    title: "Dream Center of Forsyth County",
    location: "Winston-Salem, North Carolina",
    link: "https://dreamcenterforsyth.com/",
  },
  {
    number: 4,
    id: "H0qLkmp",
    title: "Forsyth Humane Society",
    location: "Winston-Salem, North Carolina",
    link: "https://forsythhumane.org/",
  },
  {
    number: 5,
    id: "mHHiLYY",
    title: "H.A.R.R.Y Veterans Community Outreach Services",
    location: "Winston-Salem, North Carolina",
    link: "https://www.harry4you.org/welcome",
  },
  {
    number: 6,
    id: "DW4b7Hu",
    title: "HOPE of Winston-Salem",
    location: "Winston-Salem, North Carolina",
    link: "https://hopews.org/",
  },
  {
    number: 7,
    id: "HQkglMX",
    title: "Junior League of Winston-Salem",
    location: "Winston-Salem, North Carolina",
    link: "https://www.jlws.org/",
  },
  {
    number: 8,
    id: "baohoCZ",
    title: "Mary Reynolds Babcock Foundation",
    location: "Winston-Salem, North Carolina",
    link: "https://www.mrbf.org/",
  },
  {
    number: 9,
    id: "a586ZvS",
    title: "Reynolds Kate B Charitable Trust",
    location: "Winston-Salem, North Carolina",
    link: "https://kbr.org/",
  },
  {
    number: 10,
    id: "Az2VPcj",
    title: "Samaritan Ministries",
    location: "Winston-Salem, North Carolina",
    link: "https://www.samaritanforsyth.org/",
  },
  {
    number: 11,
    id: "lIExTVJ",
    title: "SECU Family House",
    location: "Winston-Salem, North Carolina",
    link: "https://www.familyhousews.org/ ",
  },
  {
    number: 12,
    id: "E9Glw9b",
    title: "Springwell Network",
    location: "Winston-Salem, North Carolina",
    link: "http://grphms.com/",
  },
  {
    number: 13,
    id: "WPNfyyw",
    title: "United Way of Forsyth County",
    location: "Winston-Salem, North Carolina",
    link: "https://www.forsythunitedway.org/",
  },
  {
    number: 14,
    id: "iKjIziO",
    title: "Winston Salem Rescue Mission",
    location: "Winston-Salem, North Carolina",
    link: "https://wsrescue.org/",
  },
  {
    number: 15,
    id: "dfJfJJ9",
    title: "Youth Achieving Moral Maturity",
    location: "Winston-Salem, North Carolina",
    link: "https://kgyamm.org/ ",
  },
];

export default CardElements;
